apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
  namespace: default
  labels:
    app: billing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing-container
          image: mouadalt/billing-service:v1
          env:
            - name: eureka.instance.prefer-ip-address
              value: 'true'
            - name: server.port
              value: '8083'
            - name: spring.application.name
              value: BUILLING-SERVICE
            - name: spring.h2.console.enabled
              value: 'true'
            - name: spring.cloud.discovery.enabled
              value: 'true'
            - name: spring.datasource.url
              value: jdbc:h2:mem:billing-db
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-server:8761/eureka
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: billing-service
  labels:
    run: billing-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: LoadBalancer
  selector:
    app: billing
