apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: default
  labels:
    app: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: mouadalt/e-banking-microservices:v1
          env:
            - name: eureka.instance.prefer-ip-address
              value: 'true'
            - name: server.port
              value: '8082'
            - name: spring.application.name
              value: CUSTOMER-SERVICE
            - name: spring.h2.console.enabled
              value: 'true'
            - name: spring.cloud.discovery.enabled
              value: 'true'
            - name: spring.datasource.url
              value: jdbc:h2:mem:customer-db
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-server:8761/eureka
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: customer-service
  labels:
    run: customer-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
  selector:
    app: customer
